---
title: "Obtaining LottoMax data"
author: "Adam Shen"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
    highlight: tango
    theme:
      bootswatch: cosmo
      base_font:
        google: "IBM Plex Sans"
      code_font:
        google: "IBM Plex Mono"
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, eval=FALSE, warning=FALSE, message=FALSE)
```

# Packages

```{r}
library(rvest)
library(dplyr)
library(purrr)
```

# Create function to get data for each year

## Try 2021

```{r}
url2021 <- "https://www.lottomaxnumbers.com/numbers/2021"

nums2021 <- read_html(url2021) %>%
  html_element(css="table") %>%
  html_table(header=TRUE)
```

## General case

```{r}
getnums <- function(year){
  yearurl <- paste0("https://www.lottomaxnumbers.com/numbers/", year)
  
  read_html(yearurl) %>%
    html_element(css="table") %>%
    html_table(header=TRUE)
}
```

# Get the data

Just going to row-bind it all.

```{r}
input_years <- 2019:2021 %>%
  set_names(., nm=.)

lottomax <- map_dfr(input_years, getnums, .id="year")
```

Names are a bit long... Rename them.

```{r}
lottomax <- lottomax %>%
  rename("date" = "Result Date:", "result" = "Draw Result:")

saveRDS(lottomax, "./data/lottomax.RDS", version=2)
```

# Session info

```{r, eval=TRUE}
sessioninfo::package_info(
  pkgs = c("rvest", "dplyr", "purrr", "bslib", "rmarkdown"),
  dependencies = FALSE
)
```

```{r, include=FALSE}
rmarkdown::render("01-data.Rmd", output_dir="./output")
```
