---
title: "Cleaning LottoMax data"
author: "Adam Shen"
date: "June 22, 2021"
output: 
  html_document:
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
    highlight: tango
    theme:
      bootswatch: cosmo
      base_font:
        google: "IBM Plex Sans"
      code_font:
        google: "IBM Plex Mono"
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE)
```

# Packages

```{r}
library(tidyverse)
library(lubridate)
```

# Load the data

```{r}
lottomax <- readRDS("./data/lottomax.RDS")

head(lottomax, n=10)

as.character(lottomax[1,2])

as.character(lottomax[1,3])
```

# Clean the data

To do:

- `date`: remove the non-space characters and the "With Max Millions!" phrase
- `result`: remove the non-space characters and reformat this column somehow so
that the numbers are a easy to access and manipulate
- Also need to keep in mind that the last number is a "bonus" number



















# Session info

```{r, echo=FALSE}
sessioninfo::package_info(
  pkgs = c("lubridate"),
  dependencies = FALSE
)
```


```{r, eval=FALSE, include=FALSE}
rmarkdown::render("02-clean.Rmd", output_dir="./output")
```
